# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set:
  - pipefail

silent: false

includes:
  hw01:
    taskfile: ./hw01/Taskfile.yml
    optional: true
  hw02:
    taskfile: ./hw02/Taskfile.yml
    optional: true
  hw03:
    taskfile: ./hw03/Taskfile.yml
    optional: true
  hw04:
    taskfile: ./hw04/Taskfile.yml
    optional: true

tasks:
  default:
    silent: true
    cmds:
      - task --list --color
