# compose.yaml

services:
  syn-tg-bot:
    build:
      context: .
      dockerfile: ../dev/Dockerfile
    ports:
      - 8000:8000  # Должно соответствовать METRICS_PORT
    environment:
      - METRICS_PORT=8000
    env_file:
      - .env